apiVersion: v1
kind: Service
metadata:
  name: h2e-service
  labels:
    app: h2e
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30006
    protocol: TCP
    name: http
  selector:
    app: h2e

