apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-text-editor-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  - host: shared-text-editor.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shared-text-editor-service
            port:
              number: 80

